# This is not particullary usefull in any sense except if we are deploying to NGINX

version: 0.2
phases:
  pre_build:
    commands:
      - npm install
      - cd client
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ./